options:
  logging: CLOUD_LOGGING_ONLY
# steps:
#   # Install Firebase CLI
#   - name: 'gcr.io/cloud-builders/npm'
#     args: ['install', '-g', 'firebase-tools']
#     id: install-firebase

#   - name: 'gcr.io/firebase-community/firebase-tools'
#     args: ['deploy', '--only', 'hosting:testingg', '--project', '637848627669']
#     entrypoint: 'firebase'
#     id: deploy-firebase

steps:
  # Install and deploy using Firebase CLI
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '-g', 'firebase-tools', '&&', 'firebase', 'deploy', '--only', 'hosting:testiingg', '--project', '637848627669']
    id: deploy-firebase

